.TH SH2DB 1 "$Date: 2008/10/25 11:31:19 $"
.SH NAME
sh2db - convert Seismic Handler data to Antelope db
.SH SYNOPSIS
.nf
sh2db db [-e -3c -RFmode -pf pffile -v] < filelist
.SH DESCRIPTION
.LP
Seismic Handler is a data processing package developed by 
Klaus Stemmler.  This program reads Seismic Handler Q-files
to produce a Datascope database.  What tables are produced
depend on various options that can be used in the program.
.LP
Seismic Handler Q-files are of a class of seismic formats
that separate header data from their equivalent waveform 
data files.  Seismic Handler header files are ascii, while
the waveform data are stored as binary float samples 
stored in a parallel file.  The two files are linked by a common
name.ext format where the "name" is constant and the header
and data files have different 3 character extensions (QHD
and QBD respectively).  The base mode of operation of this program
is to always build a wfdisc table to index the QBD file.  
This component of the program is not optional.  The default
behavior is to produce only this wfdisc table.  When any 
of the option flag are used one or more of the following
tables will be produced:  wfprocess, evlink, sclink, 
orient, event, origin, and arrival.  
.SH OPTIONS
.IP -3c
If this flag appears on the command line it is assumed the
data in ALL the Q files to be processed are organized
as three-component triplets in some rational order.  
If the number of traces in a Q file is not a multiple of 3 
a diagnostic will be issued an that file will be skipped.  
This processing initiates two major additions to the output.
First, besides wfdisc a parallel set of attributes are written
to the four related tables wfprocess, evlink, sclink, and orient.
The most important thing these allow is variable orientation 
channels for each channel.  
.IP -e
This is a flag to initiate "event" mode.  When event mode is 
enabled the program first attempts to load event->origin from 
the database pointed to by argument 1 of the command line.
If there is no event and/or origin table they will be created.
As Q files are read hypocenter information for events tabulated
there are posted to an internal list.  On exit the unique entries 
in this event catalog are written to event and origin.  In theory
if the database had previous event/origin entries only new events will be added
to the database, but at this writing this feature is untested. 
.IP -RFmode
This flag initiates "Receiver Mode" processing.  
If used without the -3c flag this does virtually nothing.  
In 3c mode when this flag is enabled two things happen.  
First, when used in combination with the enable_time_skewing
parameter (see below) the program will hunt for the peak amplitude
on the component tagged with channel code L and skew the start time
to make that time identical to the predicted arrival time for 
theh P wave.  
First, in this mode calib in the Q file header is ignored.  
When the enable_time_skewing parameter is set true 
AND the peak_normalization parameter is set true calib is 
scaled to force the peak amplitude on L to have an amplitude of 1.0.
Otherwise calib is simply set to 1.0 for all data.
.IP -pf
Use pffile as an alternative to the standard sh2db.pf. 
.IP -v
Enable verbose mode.
.SH FILES
.LP
The program expects to read a list of QBN files from stdin.  This
list can and usually should be a path that includes a directory 
that will be translated into a dir attribute in the output wfdisc.
Each QBN file is expected to have a parallel QHD file containing
the Seismic Handler header linked to the related QBN file.  The 
QBN files are indexed to build a wfdisc entry for each trace stored
in these QBN files.  When 3C mode is enabled new files are written
in the directory with a new appendage that contain data in a 3c 
bundle format allowed by the wfproces table.  These files have a 
parallel structure to the Q file.  That is if we had a QBN file
with the name wf/BERG_PRF.QBN, binary files will be written with 
the name wf/BERG_PRF.3C that contains the 3c bundle data.  
The 3C are always in standard coordinates (x1 - postive East,
x2 - postive North, and x3 - postive up).  
.SH PARAMETER FILE
.LP
The parameter file for this program is fairly lengthy, but 
many of the parameter should not be altered by the user.
I first describe parameters the user may wish to alter and then
briefly document the purpose of parameters that should not normally 
be changed.
.ce
\fIParameters you might change\fR
.fi
.PP
\fIema_key\fR can be used if the emergence angle for 
LQT data was measured and stored in a named trace attribute
in Seismic Handler.  By default this is set to "none" which 
is taken to mean ema should be computed.
.PP
\fIv0\fR is a surface velocity (km/s) used to produce an
estimate of emergence angle (ema) for LQT data.  Unless
one enables extracting this parameter with \fIema_key\fR
ema is calculated from the P wave slowness vector and 
Snell's law using this parameter.  
.PP
\fInetname\fR 
This parameter is used to define the network attribute
in the output database.
.PP
\fIenable_time_skewing\fR 
is a boolean used to enable time skewing of RFmode data.
By default this feature is off.  When enabled and when 
the -RFmode option is set trace start times will be
skewed to force the peak amplitude on the L component
(adjustable in theory, but avoid - see below) to coincide 
with the predicted P arrival time.  This feature is necessary
in the authors experience
on RF data generated by Seismic Handler because it does not
handle the time ambiguity in a spiking filter correctly.
.PP
\fImaximum_time_skew\fR 
This parameter determines a cutoff on the allowed time skew
when enable_time_skewing is true.  This is a sanity check
to avoid locking onto edge transients.  
.PP
\fIttmethod\fR 
and 
\fIttmodel\fR 
set the travel time calculator used for two contexts.  
When using LQT coordinates this calculator is used to compute
the slowness vector of the incident P wave.  In addition the 
predicted time for P is used when \fIenable_time_skewing\fR
is enabled.
.PP
\fItime_zero_component\fR 
is by default L for the L of LQT.  In principle this could
be something else like Z.
.PP
\fIpeak_normalization\fR 
is a boolean that controls normalization when in -RFmode.  
When true data will be normalized to force the peak amplitude
on all L components to be exactly 1.0.  Otherwise data are 
assumed properly scaled to approximately satisfy this condition.
.PP
\fIinitial_timestamp\fR 
Seismic Handler does not maintain receiver geomtry in trace
headers so this data must be obtaind elsewhere.  This code
uses the SeismicArray object in the seipp library.  
The SeismicArray object refreshes itself whenever geometry
changes when a stations ondate or offdate become inconsistent
with the time interval of a trace.  This parameter should be
set to a rough estimate of the start time of the data being processed.
.PP
\fIdatatype\fR
should be set to either t4 or u4. Seismic Handler saves all 
trace data as host floats. Set this depending on the endian order
of the machine on which the data were processed.
.PP
\fIsave_relative_time_data\fR is ignored unless -3c and -RFmode mode are 
both enabled.  When set true 3c data will be stored in two formats.
The normal absolute time data and second relative time data
set with 0 as the predicted P arrival time.  
When this is enabled two other parameters are required
called \fIrelative_time_window_start\fR and
\fIrelative_time_window_end\fR.  These define a time gate
are around the 0 time defined by the predicted P arrival time
reference time.  
.PP
\fIP_arrival_component\fR and \fIS_arrival_component\fR define
chan attributes tagged to arrival rows.  If you have mixed 
channel code data (e.g. HHZ and BHZ data) limit the Q file
lists to common channel code names to avoid a lot of subsequent
database cleanup.
.ce
\fIParameters that should not be changed by the user\fR
.fi
.PP
\fISHHdrAttributes\fR 
This is Tbl list that defines the mapping of Seismic Handler
names to internal names that are mapped to css3.0 database
attribute names.  Changing this carelessly is nearly 
certain to cause this program to crash.  This was not hard
wired to allow changes to account for possible changes in 
seismic hander naming conventions.  Since the header 
format is highly extensible I judged this wise.
\fIwfdisc_attribute_list\fR 
.PP
\fIwfprocess_attribute_list\fR 
is a list of trace attributes to be written to the wfprocess table.
.PP
\fIwfdisc_attribute_list\fR 
is a list of trace attributes to be written to the wfdisc table.
.PP
\fIeventdb_attribute_list\fR 
is a list of attributes to be saved from the EventCatalog 
object.  
.PP
\fIschema\fR 
default is css3.0. Extensions of css3.0 may work, but change
at your own risk.

.SH DIAGNOSTICS
.SH "SEE ALSO"
.nf
http://www.szgrf.bgr.de/sh-doc/index.html
.fi
.SH "BUGS AND CAVEATS"
.LP
The new files created in 3c mode will be quietly appended forever.  
i.e. if the program is run multiple times on the same data multiple
copies of the same data will be written in these files.
.SH AUTHOR
.nf
Gary L. Pavlis
Department of Geological Sciences
Indiana University
pavlis@indiana.edu
.fi
.\" $Id: sh2db.1,v 1.2 2008/10/25 11:31:19 pavlis Exp $
