BIN=testmsw

include $(ANTELOPEMAKE)  	
    CXXFLAGS += -I/Users/pavlis/foreignsrc/libmseed
    LDFLAGS += -L/Users/pavlis/foreignsrc/libmseed -lmseed
OBJS=testmsw.o MSWriter.o 
$(BIN) : $(OBJS)
	$(RM) $@
	$(CXX) $(CCFLAGS) -o $@ $(OBJS) $(LDFLAGS) $(LDLIBS)
