BIN=xcoravg

cflags=-g -I$(MATLAB)/include -DMATLABDEBUG
ldflags=-lseispp -ltrvltm -lgclgrid $(TRLIBS) $(DBLIBS) -lperf -lm
ldlibs=-lseispp -ltrvltm -lgclgrid $(MATLABLIB) -lmatlabprocessor  \
 -lgclgrid -lseispp -leng -lmx -lut -lmat $(TRLIBS) $(DBLIBS) -lperf -lm

include $(ANTELOPEMAKE)
include $(ANTELOPEMAKE).local
CXXFLAGS += $(MATLABINCLUDE)
OBJS=xcoravg.o
$(BIN) : $(OBJS)
	$(RM) $@
	$(CXX) $(CXXFLAGS) -o $@ $(OBJS) $(LDFLAGS) $(LDLIBS)
