#include <stdio.h>
#include <string.h>
#include <malloc.h>
#include <unistd.h>
#include "stock.h"
#include "coords.h"
#include "db.h"
#include "db_ratio.h"
/*
This function writes a spectral result stored in array spec to an output file 
defined with name formed as dir/dfile.  spec is assumed to hold nfreq 
floats.  

Normal return is foff returned by ftell (0 or position appended from)
Any negative return indicates an error:

	-1 - cannot open file
	-2 - write error


Author:  Gary Pavlis
Written:  August 1994
Modified:  July 1995 for revised spectral program now called mwspec.  
Changed behaviour such that when a file doesn't exist it is created.
and the function returns 0.  If the file name exists, the function seeks
to the end of the file and appends the given data onto the end of the 
given file.  In this condition it returns foff (end of previous file)
This was done to reduce the number of files generated by this program.
(see also save_spectrum below)
*/
  
long write_spectrum(float *spec,int nfreq,char *dir, char *dfile)
{
	char *fname;
	FILE *fp;
	int size;
	long foff;

	size = strlen(dir) + strlen(dfile) + 4;
	if( (fname = (char *) malloc(size)) == NULL) return(-3);
	strcpy(fname,dir);
	strcat(fname,"/");
	strcat(fname,dfile);
	if( (fp = fopen(fname,"a")) == NULL) return(-1);
	fseek(fp,0L,2);
	foff = ftell(fp);
	if( (fwrite(spec,sizeof(float),nfreq,fp)) != nfreq) return (-2);
	free(fname);
	fclose(fp);
	return(foff);
}
int save_spectrum(Dbptr db,Spectrum *s)
{
	int psid;
	int dberr;
	int foff=0;
	
	char fname[40];  

	db = dblookup(db,0,"psdisc",0,0);
	psid = dbnextid(db,"psid");

	if(s->index == -1) return(1);
	/* Because we can append to dfile and get foff from write_spectrum
	we need to write the data first.  For this reason, however, if 
	dbaddv fails below it must be a fatal error to preventing endless
	quantities of garbage in the output files with no corresponding
	entries in the database. */

	if((foff=write_spectrum(s->spec,s->nfreq,s->dir,s->dfile)) < 0)
	{
		/* this should also be a fatal error */
		return (-1);
	}

	if(( dberr = dbaddv(db,0,
			"sta",s->sta,
			"chan",s->chan,
			"sname",s->sname,
			"arid",s->arid,
			"time",s->time,
			"psid",psid,
			"chanid",s->chanid,
			"jdate",s->jdate,
			"endtime",s->endtime,
			"phase",s->phase,
			"auth",s->auth,
			"freq0",s->freq0,
			"nfreq",s->nfreq,
			"df",s->df,
			"rayleigh",s->rayleigh,
			"tbp",s->tbp,
			"sscale",s->sscale,
			"pstype",s->pstype,
			"datatype",s->datatype,
			"dir",s->dir,
			"foff",foff,
			"dfile",s->dfile, 0 ) ) < 0  )
	{
		fprintf(stderr,"dbaddv error:  return code = %d\n",dberr);
		return(-2);
	}
	return(0);
}
void save_spectrum_error(Spectrum *s,int code)
{
	fprintf(stderr,"Warning (save_spectrum):  Error processing %s %s %s %s\n",
		s->sta,s->chan,s->sname,epoch2str(s->time,"%y%j%k"));
	switch(code)
	{
	case (1):
		fprintf(stderr,"Attempt to write unused channel\n");
		break;
	case (-1):
		fprintf(stderr,"Error writing spectral disk file\n");
		break;
	case (-2):
		complain(0,"Error appending to db psdisc table\n");
		break;
	case (-3):
		die(1,"malloc error creating filename string\n");
	default:
		fprintf(stderr,"FATAL:  unrecognized error code from save_spectrum\n");
		fprintf(stderr,"Memory leak assumed.  Exiting\n");
	}
}
		

